In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.4


In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/anaconda\\Library\\include']
blas_opt_in

In [4]:
arr=np.zeros(10)

In [5]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr[4]=1

In [7]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
arr=np.arange(10,49)

In [9]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [10]:
arr=np.arange(10)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
data=np.arange(9).reshape(3,3)

In [14]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr=np.nonzero([1,2,0,0,4,0])

In [16]:
arr

(array([0, 1, 4], dtype=int64),)

In [17]:
data=np.eye(3)

In [18]:
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
data=np.random.random((3,3,3))

In [22]:
data

array([[[0.82775921, 0.31103827, 0.71783455],
        [0.45590724, 0.02137093, 0.65407081],
        [0.64636884, 0.13002599, 0.56166083]],

       [[0.93683767, 0.39344402, 0.54137499],
        [0.18084813, 0.41686544, 0.46421079],
        [0.35185875, 0.95990719, 0.76851238]],

       [[0.8061099 , 0.53262354, 0.70194689],
        [0.37145403, 0.89975415, 0.3235865 ],
        [0.56516496, 0.88432483, 0.57359916]]])

In [23]:
data=np.random.random((10,10))

In [24]:
data

array([[0.16005096, 0.6673047 , 0.94210039, 0.71447448, 0.70389648,
        0.95321654, 0.98150924, 0.6337719 , 0.95432018, 0.97880891],
       [0.16189807, 0.16349398, 0.72121666, 0.37674035, 0.59148932,
        0.22666028, 0.74591226, 0.69537628, 0.02574251, 0.47441444],
       [0.6663205 , 0.73384745, 0.47595977, 0.16133091, 0.47956484,
        0.35832579, 0.73701305, 0.57895586, 0.02618138, 0.06800002],
       [0.67047101, 0.05455073, 0.74492669, 0.39597446, 0.18479121,
        0.93264492, 0.58950381, 0.77697182, 0.4732389 , 0.78347762],
       [0.32556622, 0.20596646, 0.16064115, 0.48749525, 0.61634885,
        0.29350551, 0.21117767, 0.22434236, 0.95647463, 0.47301558],
       [0.54701382, 0.12403758, 0.41609606, 0.65844007, 0.00996674,
        0.04366838, 0.57927389, 0.25030996, 0.17203427, 0.81287373],
       [0.20573583, 0.27407549, 0.97503836, 0.48734334, 0.09646702,
        0.91529076, 0.8765122 , 0.43604758, 0.42152717, 0.62297173],
       [0.68485629, 0.0375731 , 0.0687900

In [25]:
np.max(data)

0.9870544276766439

In [26]:
np.min(data)

0.009966741433031334

In [27]:
arr=np.random.randn(30)

In [28]:
arr

array([-0.34888817,  0.2729063 ,  2.12926361,  1.41265896,  0.96583239,
       -0.48142988,  0.57316183,  0.26103156,  0.3364999 , -0.3452077 ,
       -0.68227215, -0.60294273,  0.77450211,  1.79226108, -0.78480087,
        0.20664358,  0.36362602, -0.35391495, -0.83381821,  1.12313096,
       -1.24089725, -0.35222429,  0.45014716, -0.95533957,  2.69876474,
       -2.49856903, -0.99638513, -0.36217098,  0.0216557 , -0.56009356])

In [29]:
arr.mean()

0.06610438060159532

In [30]:
data=np.ones((4,4))

In [31]:
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
data[1:-1,1:-1]=0

In [36]:
data

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [37]:
data=np.ones((4,4))

In [38]:
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
data=np.pad(data,pad_width=1,mode='constant',constant_values=0)

In [40]:
data

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [41]:
data=0*np.nan

In [42]:
data

nan

In [44]:
print(np.nan==np.nan)

False


In [45]:
print(np.inf>np.nan)

False


In [46]:
print(np.nan-np.nan)

nan


In [47]:
print(0.3==0.1*3)

False


In [48]:
data=np.diag(1+np.arange(4),k=-1)

In [49]:
data

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [50]:
data=np.zeros((8,8),dtype=int)

In [51]:
data[1::2,::2]=1

In [52]:
data[::2,1::2]=1

In [53]:
data

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [54]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [55]:
data=np.tile(np.array([[0,1],[1,0]]),(4,4))

In [56]:
data

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [65]:
data=np.random.random((5,5))

In [66]:
data

array([[0.07075511, 0.74803572, 0.77760538, 0.18562378, 0.61455356],
       [0.48260359, 0.91608305, 0.26290386, 0.22785818, 0.61554922],
       [0.72027558, 0.23765515, 0.63472971, 0.23536468, 0.41144766],
       [0.34418308, 0.68079886, 0.77747184, 0.38824398, 0.54412543],
       [0.07678621, 0.86312668, 0.13983921, 0.02977301, 0.21213842]])

In [67]:
m,n=data.max(),data.min()

In [68]:
data=(data-n)/(m-n)

In [69]:
data

array([[0.04623901, 0.81039667, 0.84375934, 0.17584227, 0.65979231],
       [0.51091667, 1.        , 0.26303532, 0.22349422, 0.66091569],
       [0.77907565, 0.23454788, 0.68255652, 0.2319636 , 0.43063334],
       [0.35474051, 0.73453512, 0.84360867, 0.40445325, 0.58033012],
       [0.05304374, 0.94025074, 0.12418476, 0.        , 0.20575803]])

In [70]:
color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])

In [71]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [72]:
data=np.dot(np.ones((5,3)),np.ones((3,2)))

In [73]:
data

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])